package update

import (
	"crypto/ed25519"
	"encoding/base64"
	"fmt"
)

// The public halves of the keys a release may be signed with, and the
// whole of what this agent will ever trust.
//
// SPEC §15.2: because there is no code-signing certificate, "signed
// package" means our own signature. The agent embeds a public key,
// every release is signed with the private half, and the agent
// verifies a release before doing anything with it.
//
// There are two, and the second one is the answer to a question F10
// §4.1 asks and this project could not otherwise answer: what happens
// if the key is lost or compromised. Every installed agent trusts what
// it was built with and can never be told to stop; without a second
// slot, a lost primary means every user reinstalls by hand, found out
// at the worst possible moment. With one, the next release is signed
// with the spare, every agent already in the field accepts it, and the
// release after that ships a build whose trust set no longer contains
// the compromised key.
//
// That only works if the two are kept apart. The primary's private
// half is the LIRO_RELEASE_SIGNING_KEY secret of the `release`
// deployment environment and nothing else — an environment rather than
// a repository secret, because the environment's own rule is what
// admits only a v* tag, and a repository secret is readable from any
// ref this workflow runs on. The spare's private half is offline, and
// putting it into CI is the act of retiring the primary, not a
// convenience. A spare that lives beside the primary is not a spare.
//
// Generated by scripts/genreleasekey, run by the owner on his own
// machine. Neither private half has ever been generated by, printed
// to, or held by the agent that wrote this file; neither is in this
// repository, in any artefact, or in any log.
//
// This is the third generation of key material for this slot pair, and
// the first that is in use. Two earlier generations exist in this
// repository's history and in terminal output, and neither was ever
// trusted by a released build — D-238 records which values they were
// and why each was discarded, so that finding one later does not raise
// the question a second time.
const (
	// releaseKeyPrimary signs every release today.
	releaseKeyPrimary = "Zvv9hK4M+KUBnyyLEKeE8IOYMn+jIULhViFNrWXjnv8="

	// releaseKeySpare has never signed anything and is not meant to
	// until it has to. It is embedded so that it can.
	releaseKeySpare = "VJL9LrGYHzz6RrWEkJk0Oqm0GFA+/fbAsMRy1HyRyfI="
)

// TrustedKeys returns the public keys this build accepts a release
// signature from.
//
// It panics on a malformed constant rather than returning an error,
// and that is deliberate: these are compile-time constants in this
// repository, so a bad one is a bug in the build rather than a
// condition at run time — and the alternative, a trust set that
// silently comes back one key short, is the failure this whole
// mechanism exists to prevent. i18n.loadCatalogues panics on its own
// embedded data for the same reason.
func TrustedKeys() []ed25519.PublicKey {
	return []ed25519.PublicKey{
		mustKey("primary", releaseKeyPrimary),
		mustKey("spare", releaseKeySpare),
	}
}

func mustKey(role, b64 string) ed25519.PublicKey {
	raw, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		panic(fmt.Sprintf("update: the %s release key is not base64: %v", role, err))
	}
	if len(raw) != ed25519.PublicKeySize {
		panic(fmt.Sprintf("update: the %s release key is %d bytes, want %d", role, len(raw), ed25519.PublicKeySize))
	}
	return ed25519.PublicKey(raw)
}
