package main

import (
	"fmt"
	"sort"
	"strings"
)

// IntentFamilyColor maps each of the four outcome-intent families
// (Task 6, F5 first-real-run review) to the token that colours it. It
// is the single place that decision is made: the .liro-outcome-<name>
// classes in intentsCSS below are generated directly from this map by
// intentOutcomeCSS, so a caller displaying an outcome (audit log,
// certificates window) picks one of these four names and nothing
// downstream — Go or CSS — ever chooses a colour of its own for it.
//
// approved/succeeded -> positive, denied/cancelled -> warning,
// failed -> negative, partial -> caution (D-0xx documents the mapping
// and why "caution" and "warning" are kept visually distinct).
var IntentFamilyColor = map[string]string{
	"positive": "--liro-color-positive",
	"warning":  "--liro-color-warning",
	"negative": "--liro-color-negative",
	"caution":  "--liro-color-caution",
}

// intentOutcomeCSS generates one ".liro-outcome-<name> { color:
// var(<token>); }" rule per entry of IntentFamilyColor, sorted by name
// for a stable, diffable output.
func intentOutcomeCSS() string {
	names := make([]string, 0, len(IntentFamilyColor))
	for name := range IntentFamilyColor {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	for _, name := range names {
		fmt.Fprintf(&b, ".liro-outcome-%s {\n  color: var(%s);\n}\n\n", name, IntentFamilyColor[name])
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// intentsCSS defines the small set of reusable component classes every
// window's own page builds on (F5 §4.1's "intent classes"), so a
// window's own stylesheet only ever composes these plus layout — it
// never needs a colour or spacing value of its own, which is what
// keeps scripts/checkcss's hex-literal rule meaningful rather than
// something every page routes around.
var intentsCSS = intentsCSSBase + "\n" + intentOutcomeCSS() + "\n" + intentsCSSSteps

const intentsCSSBase = `/* Generated by scripts/synctokens. Do not edit by hand — see D-086. */

* {
  box-sizing: border-box;
}

/* [hidden] is how every page in this project shows and hides a screen
   or a control (consent.js's showState, the stamp corner selector, the
   empty-list notice). The browser's own "[hidden] { display: none }"
   comes from the user-agent stylesheet, and an author rule as ordinary
   as ".liro-field { display: flex }" outranks it in the cascade
   regardless of specificity — which is how a hidden element kept
   displaying. Verified by looking at the window: the corner selector
   was on screen with its checkbox unticked, while the page's own
   el.hidden property was correctly true, so no property-level test saw
   it. !important is the one thing that makes the intent unconditional
   here. */
[hidden] {
  display: none !important;
}

body {
  margin: 0;
  font-family: var(--liro-font-family);
  font-size: var(--liro-font-size-body);
  line-height: var(--liro-line-height-body);
  color: var(--liro-color-text-primary);
  background: var(--liro-color-bg);
}

/* Every interactive element gets a visible focus ring in the token
   colour (F5 §5.6 / SPEC §10.3) — never suppressed with outline: none
   without a var(--liro-color-focus-ring) replacement. */
:focus-visible {
  outline: 2px solid var(--liro-color-focus-ring);
  outline-offset: 2px;
}

.liro-display {
  font-size: var(--liro-font-size-display);
  font-weight: var(--liro-font-weight-bold);
  color: var(--liro-color-text-primary);
  margin: 0;
}

.liro-heading {
  font-size: var(--liro-font-size-heading);
  font-weight: var(--liro-font-weight-semibold);
  color: var(--liro-color-text-primary);
  margin: 0;
}

.liro-text-secondary {
  color: var(--liro-color-text-secondary);
}

.liro-text-small {
  font-size: var(--liro-font-size-small);
  color: var(--liro-color-text-secondary);
}

.liro-btn {
  font-family: inherit;
  font-size: var(--liro-font-size-body);
  font-weight: var(--liro-font-weight-semibold);
  border-radius: var(--liro-radius-sm);
  padding: var(--liro-space-3) var(--liro-space-5);
  border: 1px solid transparent;
  cursor: pointer;
}

.liro-btn-primary {
  background: var(--liro-color-brand);
  color: var(--liro-color-text-on-brand);
}
.liro-btn-primary:hover {
  background: var(--liro-color-brand-hover);
}
.liro-btn-primary:active {
  background: var(--liro-color-brand-active);
}

.liro-btn-secondary {
  background: var(--liro-color-neutral);
  color: var(--liro-color-text-primary);
  border-color: var(--liro-color-border);
}
.liro-btn-secondary:hover {
  background: var(--liro-color-neutral-hover);
}
.liro-btn-secondary:active {
  background: var(--liro-color-neutral-active);
}

/* Task 3 (F5 third-real-run review): the quietest of the three button
   weights, for an action that must stay reachable without competing
   with the two real choices beside it. Two neutral buttons side by side
   read as equals, which is wrong wherever one of them is Cancel — so
   this one gives up the filled background and the border entirely and
   keeps only secondary text, and takes the neutral fill back on hover
   so it still answers to the pointer. Colours from tokens, like every
   other rule here. */
.liro-btn-quiet {
  background: transparent;
  color: var(--liro-color-text-secondary);
  border-color: transparent;
}
.liro-btn-quiet:hover {
  background: var(--liro-color-neutral);
  color: var(--liro-color-text-primary);
}
.liro-btn-quiet:active {
  background: var(--liro-color-neutral-active);
  color: var(--liro-color-text-primary);
}

/* Task 2 (F5 second-real-run review): a compact button for an action
   that sits inline next to the value it acts on (the Details card's
   "Copy" next to the batch fingerprint), rather than in its own actions
   row. Same colours and shape as any other button — only the padding
   and weight differ. */
.liro-btn-compact {
  padding: var(--liro-space-1) var(--liro-space-2);
  font-size: var(--liro-font-size-small);
  font-weight: var(--liro-font-weight-regular);
}

.liro-btn:disabled {
  background: var(--liro-color-disabled-bg);
  color: var(--liro-color-disabled-text);
  cursor: default;
}

/* Every text/password input shares this shape (Task 5): taller than
   the browser default, consistent border and padding from tokens, and
   a brand-coloured border on focus so the visible :focus-visible
   outline below is not the only thing that changes. */
input[type="text"],
input[type="password"] {
  font-family: inherit;
  font-size: var(--liro-font-size-body);
  color: var(--liro-color-text-primary);
  background: var(--liro-color-surface-raised);
  border: 1px solid var(--liro-color-border);
  border-radius: var(--liro-radius-sm);
  padding: var(--liro-space-2) var(--liro-space-3);
}
input[type="text"]:focus-visible,
input[type="password"]:focus-visible {
  border-color: var(--liro-color-brand);
}

.liro-badge {
  display: inline-block;
  align-self: flex-start;
  font-size: var(--liro-font-size-small);
  font-weight: var(--liro-font-weight-semibold);
  border-radius: var(--liro-radius-full);
  padding: 2px var(--liro-space-2);
}

.liro-badge-test-key {
  background: var(--liro-color-test-key-bg);
  color: var(--liro-color-test-key);
}

.liro-badge-qualified {
  background: var(--liro-color-surface);
  color: var(--liro-color-text-secondary);
}

.liro-badge-warning {
  background: var(--liro-color-warning-bg);
  color: var(--liro-color-warning);
}

.liro-card {
  background: var(--liro-color-surface-raised);
  border: 1px solid var(--liro-color-border);
  border-radius: var(--liro-radius-md);
  padding: var(--liro-space-3);
}

.liro-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--liro-space-2);
}

/* Task 2 (F5 second-real-run review): a flex item's default
   min-width:auto refuses to shrink below its content's intrinsic
   width, so one long unbreakable token inside a .liro-row pushed the
   whole row — and with it the card, and the window's layout — wider
   than the window itself. Every row child may shrink; long text breaks
   inside the word rather than overflowing. Values that cannot usefully
   break at all (a 64-character hex digest) are truncated in Go before
   they ever reach the page. */
.liro-row > * {
  min-width: 0;
}

.liro-wrap {
  overflow-wrap: anywhere;
}

/* Task 2 (F5 fourth-real-run review): a form field whose label sits
   above its input, left-aligned, with the input taking the full width
   beneath it. This replaces .liro-row for every labelled text input in
   the settings window. A side-by-side row divides the width between a
   label and an input, and Serbian labels are considerably longer than
   their English equivalents — "Klijentski sertifikat za servis za
   vremenske zigove (PKCS#12)" against "TSA client certificate
   (PKCS#12)" — so a row that fits in English wraps to two lines in
   Serbian regardless of how wide the window is made. Stacking gives
   the label the whole width and stops the two competing for it. */
.liro-field {
  display: flex;
  flex-direction: column;
  gap: var(--liro-space-1);
  min-width: 0;
}

.liro-field > .liro-field-label {
  color: var(--liro-color-text-secondary);
  overflow-wrap: anywhere;
}

.liro-field > input,
.liro-field > select {
  width: 100%;
}

/* A checkbox or radio keeps its label beside it — that pairing is what
   makes the control legible, and neither one is a long field label
   competing with an input for the same line. */
.liro-check {
  display: flex;
  align-items: center;
  gap: var(--liro-space-2);
}

.liro-check > span {
  min-width: 0;
  overflow-wrap: anywhere;
}

/* A <select> is styled to match the text inputs above, so a form does
   not mix the browser's default control shape with the project's. */
select {
  font-family: inherit;
  font-size: var(--liro-font-size-body);
  color: var(--liro-color-text-primary);
  background: var(--liro-color-surface-raised);
  border: 1px solid var(--liro-color-border);
  border-radius: var(--liro-radius-sm);
  padding: var(--liro-space-2) var(--liro-space-3);
}

/* Task 5 (F5 fourth-real-run review): the shape every window's page
   uses so that its action buttons are always on screen. The page is a
   fixed-height column — the window's own height, never taller — inside
   which exactly one region is allowed to grow and scroll
   (.liro-scroll-region). A primary action that scrolls off the bottom
   is the same defect as a button that does nothing, and the only way
   to make that impossible rather than merely unlikely is to stop the
   page itself from being scrollable at all. */
.liro-page {
  height: 100vh;
  display: flex;
  flex-direction: column;
}

.liro-scroll-region {
  flex: 1 1 auto;
  min-height: 0;
  overflow-y: auto;
}

/* Anything that must never be squeezed out by a growing scroll region:
   a header, an actions row, a status line. */
.liro-fixed-region {
  flex: 0 0 auto;
}

/* The heading of a status line: what happened, and where. A paragraph,
   so it carries the browser's own margins unless told otherwise. */
.liro-status-text {
  margin: 0;
  overflow-wrap: anywhere;
}

/* The files an action wrote, one row each: the name in the monospace
   family every technical value in this project uses, and beside it, in
   words, what the file is. Shared by the two windows with an Export
   button, which render the same payload in the same place.

   Neither column sets a colour: the whole status line is already
   coloured by its intent family (D-093), and the line that says the
   hash chain is broken is exactly the one that must not be quieter than
   the rest. min-width: 0 with overflow-wrap is D-096's rule — a long
   file name wraps, it never widens the window. */
.liro-status-files {
  display: grid;
  grid-template-columns: auto 1fr;
  column-gap: var(--liro-space-3);
  row-gap: var(--liro-space-1);
  margin-top: var(--liro-space-2);
  font-size: var(--liro-font-size-small);
}

.liro-status-file-name {
  font-family: var(--liro-font-family-mono);
  min-width: 0;
  overflow-wrap: anywhere;
}

.liro-status-file-detail {
  min-width: 0;
  overflow-wrap: anywhere;
}

.liro-cert-row {
  display: flex;
  flex-direction: column;
  gap: var(--liro-space-1);
  padding: var(--liro-space-3);
  border: 1px solid var(--liro-color-border);
  border-radius: var(--liro-radius-sm);
  cursor: pointer;
}

.liro-cert-row[aria-selected="true"] {
  border-color: var(--liro-color-brand);
  background: var(--liro-color-surface);
}

.liro-cert-row-disabled {
  cursor: default;
  color: var(--liro-color-disabled-text);
  background: var(--liro-color-disabled-bg);
}

/* Task 4/6: the name is the largest text in a certificate row; role and
   issuer sit under it, quieter; the thumbprint tail — sometimes the
   only thing distinguishing two certificates with an identical subject
   (SPEC §11.5) — is a quiet monospace suffix on that same line, never
   its own prominent field. */
.liro-cert-name {
  font-size: var(--liro-font-size-heading);
  font-weight: var(--liro-font-weight-semibold);
  color: var(--liro-color-text-primary);
  overflow-wrap: anywhere;
}

.liro-cert-meta {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: var(--liro-space-2);
  font-size: var(--liro-font-size-small);
  color: var(--liro-color-text-secondary);
  overflow-wrap: anywhere;
}

.liro-cert-thumb {
  font-family: var(--liro-font-family-mono);
  color: var(--liro-color-text-tertiary);
  white-space: nowrap;
}

/* Task 6: an outcome renders as a single word, right-aligned, coloured
   from the intent family it belongs to — never a hand-picked colour.
   The four .liro-outcome-<name> colour rules are appended below,
   generated from IntentFamilyColor (see intentOutcomeCSS). */
.liro-outcome {
  font-weight: var(--liro-font-weight-semibold);
  text-align: right;
  white-space: nowrap;
}

.liro-disclosure summary {
  cursor: pointer;
  color: var(--liro-color-text-secondary);
  font-size: var(--liro-font-size-small);
}

.liro-progress {
  height: 6px;
  border-radius: var(--liro-radius-full);
  background: var(--liro-color-disabled-bg);
  overflow: hidden;
}

.liro-progress > span {
  display: block;
  height: 100%;
  background: var(--liro-color-brand);
  transition: width var(--liro-motion-fast);
}

.liro-progress-indeterminate > span {
  width: 40%;
  animation: liro-indeterminate 1.2s ease-in-out infinite;
}

@keyframes liro-indeterminate {
  0% {
    margin-left: -40%;
  }
  100% {
    margin-left: 100%;
  }
}

.liro-error-box {
  background: var(--liro-color-danger-bg);
  color: var(--liro-color-danger);
  border-radius: var(--liro-radius-sm);
  padding: var(--liro-space-3);
  overflow-wrap: anywhere;
}
`

// intentsCSSSteps is the step header every step of the signing flow
// carries. It lives after the generated outcome rules because that is
// where it was written when the one-window flow was built — directly
// into internal/ui/assets/intents.css, and never into this generator,
// so running scripts/synctokens deleted it. Nothing noticed, because
// nothing ran the generator between then and now.
const intentsCSSSteps = `/* The step header: one row above every step of the signing flow,
   carrying the way back on the left and where you are on the right.

   Four small dots rather than "Korak 2 od 4" in words, because the step
   is context and not the subject of the screen — it should be readable
   at a glance and ignorable the rest of the time. The words are still
   there for anyone who needs them: the row carries them as its
   aria-label, so a screen reader says "Korak 2 od 4" and the eye sees
   four dots. */
.liro-steps {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--liro-space-2);
  min-height: 28px;
  margin-bottom: var(--liro-space-2);
}

/* The back button sits where a back button sits, and its absence must
   not move the dots: the row justifies its two ends, so the dots stay
   on the right whether or not there is anything to go back to. */
.liro-steps-back {
  flex: 0 0 auto;
}

.liro-steps-dots {
  display: flex;
  align-items: center;
  gap: var(--liro-space-1);
  margin-left: auto;
}

.liro-steps-dot {
  width: 6px;
  height: 6px;
  border-radius: var(--liro-radius-full);
  background: var(--liro-color-border-strong);
}

.liro-steps-dot-current {
  background: var(--liro-color-brand);
  /* The current step is the only one that is larger as well as
     coloured: colour alone is not a distinction everyone can see
     (SPEC §10.3). */
  width: 10px;
  height: 10px;
}

.liro-steps-dot-done {
  background: var(--liro-color-text-tertiary);
}
`
