package main

// tokensCSS is the placeholder token set (see main.go's package doc
// comment): every colour, spacing and typography value the agent's
// windows use, as CSS custom properties.
//
// --liro-color-brand is the design system's brand blue, #0078D4 (Task
// 5, F5 first-real-run review, D-0xx) — the colour every primary
// action (Save, Approve) renders in. It used to be set to the real
// Liro turquoise from D-070 (#038387, the visible signature stamp's
// logo colour, internal/pades/appearance): every button in the agent's
// windows inherited the logo colour as if it were the brand's
// interactive colour, which read as "green" buttons to an actual user
// even though no hex literal anywhere said "green" — turquoise is the
// mark's colour only and never belongs on a control (D-0xx). The logo
// itself is untouched by this change: internal/pades/appearance,
// scripts/genicon and scripts/genlogo each hold #038387 as their own
// literal, entirely independent of this token pipeline.
//
// --liro-color-neutral is the secondary-action background (Close,
// Cancel) — deliberately its own named token rather than reusing
// --liro-color-surface, so a secondary button's colour is chosen
// because it is a neutral control, not because it happens to match
// some other surface.
//
// --liro-color-positive/-warning/-negative/-caution are the four
// outcome-intent colours (Task 6): the audit log and certificates
// windows resolve an outcome to one of these four names — never to a
// literal — through IntentFamilyColor (intents.go) and its CSS
// classes below.
const tokensCSS = `/* Generated by scripts/synctokens. Do not edit by hand — see D-086. */
:root {
  /* Colour */
  --liro-color-brand: #0078d4;
  --liro-color-brand-hover: #106ebe;
  --liro-color-brand-active: #005a9e;
  --liro-color-neutral: #f3f2f1;
  --liro-color-neutral-hover: #e1dfdd;
  --liro-color-neutral-active: #edebe9;
  --liro-color-bg: #ffffff;
  --liro-color-surface: #f4f7f7;
  --liro-color-surface-raised: #ffffff;
  --liro-color-border: #d7dedd;
  --liro-color-border-strong: #aebab8;
  --liro-color-text-primary: #16211f;
  --liro-color-text-secondary: #566866;
  --liro-color-text-tertiary: #7c8b89;
  --liro-color-text-on-brand: #ffffff;
  --liro-color-focus-ring: #0969da;
  --liro-color-positive: #107c10;
  --liro-color-positive-bg: #dff6dd;
  --liro-color-warning: #8a5300;
  --liro-color-warning-bg: #fff4e0;
  --liro-color-negative: #b3261e;
  --liro-color-negative-bg: #fbe9e7;
  --liro-color-caution: #d83b01;
  --liro-color-caution-bg: #fdf1e5;
  --liro-color-danger: #b3261e;
  --liro-color-danger-bg: #fbe9e7;
  --liro-color-test-key: #7a1fa2;
  --liro-color-test-key-bg: #f3e6fb;
  --liro-color-disabled-bg: #eef1f1;
  --liro-color-disabled-text: #9aa6a4;

  /* Spacing */
  --liro-space-1: 4px;
  --liro-space-2: 8px;
  --liro-space-3: 12px;
  --liro-space-4: 16px;
  --liro-space-5: 24px;
  --liro-space-6: 32px;

  /* Typography */
  --liro-font-family: "Segoe UI", system-ui, -apple-system, sans-serif;
  --liro-font-family-mono: "Cascadia Mono", Consolas, monospace;
  --liro-font-size-display: 20px;
  --liro-font-size-heading: 16px;
  --liro-font-size-body: 13px;
  --liro-font-size-small: 12px;
  --liro-font-weight-regular: 400;
  --liro-font-weight-semibold: 600;
  --liro-font-weight-bold: 700;
  --liro-line-height-body: 1.4;

  /* Shape */
  --liro-radius-sm: 4px;
  --liro-radius-md: 8px;
  --liro-radius-full: 999px;

  /* Elevation */
  --liro-shadow-card: 0 1px 3px rgba(0, 0, 0, 0.12);

  /* Motion */
  --liro-motion-fast: 120ms;
}
`
