package main

import (
	"fmt"
	"strings"
)

// boldSubsetDataGo emits internal/pades/appearance/subset_data_bold.go.
//
// It is deliberately not a second copy of subsetDataGo's output. The
// bold face is built from the same charset() in the same sorted order
// as the regular face, so extractSubset — which assigns GIDs
// sequentially in that order — gives both faces an identical rune → GID
// numbering by construction (D-209). Emitting runeToGID twice would
// create a second table that could silently drift from the first, and
// the stamp would then draw one character in the regular face and a
// different one in the bold. What genuinely differs between two weights
// of the same family is the advance widths and the vertical metrics,
// and that is exactly, and only, what this file carries.
func boldSubsetDataGo(sf *subsetFont) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by scripts/gensubsetfont from notosans-bold-subset.ttf. DO NOT EDIT.\n\n")
	b.WriteString("package appearance\n\n")
	b.WriteString("// The bold face carries no rune -> GID table of its own: it is built from\n")
	b.WriteString("// the same character set, in the same sorted order, as the regular face, so\n")
	b.WriteString("// runeToGID (subset_data.go) addresses both — which is also why one\n")
	b.WriteString("// /ToUnicode CMap serves both embedded fonts (D-209). What differs between\n")
	b.WriteString("// two weights of one family is the metrics below.\n\n")
	b.WriteString("// gidWidthsBold holds each bold glyph's advance width in 1000-unit glyph\n")
	b.WriteString("// space (the bold face's /W array source), indexed by GID; gidWidthsBold[0]\n")
	b.WriteString("// is .notdef.\n")
	b.WriteString("var gidWidthsBold = []uint16{\n")
	for i, g := range sf.glyphs {
		w1000 := g.advance * 1000 / int(sf.unitsPerEm)
		fmt.Fprintf(&b, "\t%d, // GID %d\n", w1000, i)
	}
	b.WriteString("}\n\n")

	minX, minY, maxX, maxY := sf.bbox()
	b.WriteString("// Bold font metrics in 1000-unit glyph space, for the bold face's own\n")
	b.WriteString("// /FontDescriptor (PDF 32000-1 §9.8.1).\n")
	fmt.Fprintf(&b, "const (\n\tboldFontAscent    = %d\n\tboldFontDescent   = %d\n\tboldFontCapHeight = %d\n\tboldFontBBoxMinX  = %d\n\tboldFontBBoxMinY  = %d\n\tboldFontBBoxMaxX  = %d\n\tboldFontBBoxMaxY  = %d\n)\n",
		sf.ascent, sf.descent, sf.capHeight, minX, minY, maxX, maxY)
	return []byte(b.String())
}
