// Command gensubsetfont produces the embedded font asset F4 requires
// (SPEC §13.2, F4 §3.2): a subsetted NotoSans, containing exactly the
// characters the visual signature stamp can draw, as a Type0/CIDFontType2
// font program with Identity-H addressing.
//
// This is a developer tool, run once (and re-run only when the character
// set changes), not part of `go build`'s normal graph and never linked
// into the release binary — internal/pades/appearance only ever
// //go:embeds this program's *output*. Runtime font parsing is exactly
// what F4 §3.2 forbids ("Runtime subsetting would mean shipping a font
// parser, which is a large surface for no benefit"); a build-time
// generator using a trusted decoder (golang.org/x/image/font/sfnt, the
// Go team's own sfnt package — the same trust tier D-041 already
// extended to golang.org/x/crypto/ocsp) to read the source font is not
// that, in the same way scripts/gencerts and scripts/gentestkeys already
// use non-hand-written parsing/encoding for build-time-only artefacts
// (D-021, D-032).
//
// The subsetting *writer* (ttfbuild.go) is hand-written, not borrowed
// from a library: composite glyphs (e.g. "č" is base "c" plus a
// combining caron) are already flattened into plain contours by
// sfnt.Font.LoadGlyph, so a from-scratch TrueType "simple glyph" writer
// covers every glyph this subset needs — no composite-glyph mechanism,
// hinting bytecode, or OS/2 table (PDF's /FontDescriptor supplies the
// metrics a CIDFontType2 embedding actually uses; the font's own OS/2
// table is not consulted for that) is required for correctness here.
//
// Usage:
//
//	go run ./scripts/gensubsetfont --font <path to NotoSans-Regular.ttf>
//
// Output (committed):
//
//	internal/pades/appearance/notosans-subset.ttf
//	internal/pades/appearance/subset_data.go
//	internal/pades/appearance/charset.txt
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"

	"golang.org/x/image/font"
	"golang.org/x/image/font/sfnt"
	"golang.org/x/image/math/fixed"
)

// subsetTag is the six-uppercase-letter subset prefix F4 §3.1 requires
// ("/BaseFont /AAAAAA+NotoSans"). Real-world PDF producers usually
// randomise this to avoid collisions when several different subsets of
// the same font family, from different sources, end up in one merged
// document. That scenario cannot happen here: this project embeds at
// most one font, generated by this one program, into any document it
// signs — so a fixed tag is simpler (SPEC §0) and, unlike a random one,
// keeps this generator's own output reproducible across runs.
const subsetTag = "LIROBR"

func main() {
	fontPath := flag.String("font", "", "path to the source NotoSans-Regular.ttf")
	outDir := flag.String("out", "internal/pades/appearance", "output directory")
	flag.Parse()
	if *fontPath == "" {
		log.Fatal("gensubsetfont: --font is required")
	}

	src, err := os.ReadFile(*fontPath)
	if err != nil {
		log.Fatalf("gensubsetfont: reading %s: %v", *fontPath, err)
	}
	f, err := sfnt.Parse(src)
	if err != nil {
		log.Fatalf("gensubsetfont: parsing source font: %v", err)
	}

	runes := charset()
	sf, err := extractSubset(f, runes)
	if err != nil {
		log.Fatal(err)
	}

	ttf, err := sf.build()
	if err != nil {
		log.Fatalf("gensubsetfont: building subset: %v", err)
	}
	if err := verifySubset(ttf, sf); err != nil {
		log.Fatalf("gensubsetfont: self-verification of generated subset failed: %v", err)
	}
	if err := verifyOutlineGeometry(f, ttf); err != nil {
		log.Fatalf("gensubsetfont: outline geometry self-verification failed: %v", err)
	}

	if err := os.WriteFile(*outDir+"/notosans-subset.ttf", ttf, 0o644); err != nil {
		log.Fatalf("gensubsetfont: writing subset TTF: %v", err)
	}
	if err := os.WriteFile(*outDir+"/charset.txt", charsetFile(runes), 0o644); err != nil {
		log.Fatalf("gensubsetfont: writing charset.txt: %v", err)
	}
	formatted, err := format.Source(subsetDataGo(sf))
	if err != nil {
		log.Fatalf("gensubsetfont: generated subset_data.go is not valid Go: %v", err)
	}
	if err := os.WriteFile(*outDir+"/subset_data.go", formatted, 0o644); err != nil {
		log.Fatalf("gensubsetfont: writing subset_data.go: %v", err)
	}
	fmt.Printf("gensubsetfont: wrote %d glyphs (%d bytes) to %s\n", len(sf.glyphs), len(ttf), *outDir)
}

// extractSubset reads every rune's outline and advance width from f and
// assigns new, sequential glyph indices (1..N, sorted by rune value; 0
// is reserved for .notdef) — F4 §3.3's "build a rune → GID table."
func extractSubset(f *sfnt.Font, runes []rune) (*subsetFont, error) {
	var buf sfnt.Buffer
	upm := f.UnitsPerEm()

	m, err := f.Metrics(&buf, fixed.I(int(upm)), font.HintingNone)
	if err != nil {
		return nil, fmt.Errorf("gensubsetfont: reading font metrics: %w", err)
	}

	sf := &subsetFont{
		unitsPerEm:      uint16(upm),
		ascent:          int16(m.Ascent.Round()),
		descent:         int16(-m.Descent.Round()), // sfnt.Metrics.Descent is positive-down; hhea wants a negative value
		lineGap:         int16(m.Height.Round() - m.Ascent.Round() - m.Descent.Round()),
		capHeight:       int16(m.CapHeight.Round()),
		runeToNewGID:    map[rune]uint16{},
		createdModified: 3608668800, // 2024-05-01T00:00:00Z in seconds since 1904-01-01 — fixed, so regenerating without a source-font change reproduces byte-identical output
	}
	sf.glyphs = append(sf.glyphs, glyphOutline{}) // GID 0: .notdef, deliberately empty (F4 §3.3: a missing character is a hard error, so .notdef is never actually drawn)

	for _, r := range runes {
		gid, err := f.GlyphIndex(&buf, r)
		if err != nil {
			return nil, fmt.Errorf("gensubsetfont: looking up U+%04X: %w", r, err)
		}
		if gid == 0 {
			return nil, fmt.Errorf("gensubsetfont: source font has no glyph for required character %q (U+%04X)", r, r)
		}
		outline, err := loadOutline(f, &buf, gid, upm)
		if err != nil {
			return nil, fmt.Errorf("gensubsetfont: loading glyph for %q (U+%04X): %w", r, r, err)
		}
		newGID := uint16(len(sf.glyphs))
		sf.glyphs = append(sf.glyphs, outline)
		sf.runeToNewGID[r] = newGID
	}
	return sf, nil
}

// loadOutline decodes one glyph's outline (flattening composites, which
// sfnt.Font.LoadGlyph already does) into this project's own
// contour/point representation, negating Y along the way —
// sfnt.Segments' Y axis increases down (see LoadGlyph's own doc
// comment); TrueType's glyf table, like PDF text space, has Y increasing
// up.
func loadOutline(f *sfnt.Font, buf *sfnt.Buffer, gid sfnt.GlyphIndex, upm sfnt.Units) (glyphOutline, error) {
	segs, err := f.LoadGlyph(buf, gid, fixed.I(int(upm)), nil)
	if err != nil {
		return glyphOutline{}, err
	}
	adv, err := f.GlyphAdvance(buf, gid, fixed.I(int(upm)), font.HintingNone)
	if err != nil {
		return glyphOutline{}, err
	}

	var out glyphOutline
	out.advance = adv.Round()
	var cur []point
	flush := func() {
		if len(cur) > 0 {
			out.contours = append(out.contours, cur)
			cur = nil
		}
	}
	toPoint := func(p fixed.Point26_6, onCurve bool) point {
		return point{x: int16(p.X.Round()), y: int16(-p.Y.Round()), onCurve: onCurve}
	}
	for _, s := range segs {
		switch s.Op {
		case sfnt.SegmentOpMoveTo:
			flush()
			cur = append(cur, toPoint(s.Args[0], true))
		case sfnt.SegmentOpLineTo:
			cur = append(cur, toPoint(s.Args[0], true))
		case sfnt.SegmentOpQuadTo:
			cur = append(cur, toPoint(s.Args[0], false), toPoint(s.Args[1], true))
		case sfnt.SegmentOpCubeTo:
			// Never produced for a TrueType (glyf-outline) source font —
			// cubic curves are a CFF/PostScript-outline concept. Failing
			// loudly here is cheaper than silently mis-rendering a glyph
			// if this generator is ever pointed at a CFF-flavoured font.
			return glyphOutline{}, fmt.Errorf("cubic (CFF-style) segment in a supposedly TrueType glyph")
		}
	}
	flush()
	return out, nil
}

// verifySubset re-parses the generated font with the same trusted
// decoder used to read the source, and checks that every rune this
// subset claims to contain actually resolves to a glyph with the right
// advance width — this generator's own independent check that its
// hand-written writer produced something a real sfnt reader agrees with,
// in the same spirit as internal/pades/verify's independence from the
// signer (F3 §8/D-044), applied here to font bytes instead of CMS bytes.
func verifySubset(ttf []byte, sf *subsetFont) error {
	f, err := sfnt.Parse(ttf)
	if err != nil {
		return fmt.Errorf("re-parsing generated font: %w", err)
	}
	if got, want := f.NumGlyphs(), len(sf.glyphs); got != want {
		return fmt.Errorf("NumGlyphs = %d, want %d", got, want)
	}
	var buf sfnt.Buffer
	for r, wantGID := range sf.runeToNewGID {
		gid, err := f.GlyphIndex(&buf, r)
		if err != nil {
			return fmt.Errorf("re-parsed font: GlyphIndex(%q): %w", r, err)
		}
		if uint16(gid) != wantGID {
			return fmt.Errorf("re-parsed font: GlyphIndex(%q) = %d, want %d (cmap round-trip mismatch)", r, gid, wantGID)
		}
		adv, err := f.GlyphAdvance(&buf, gid, fixed.I(int(sf.unitsPerEm)), font.HintingNone)
		if err != nil {
			return fmt.Errorf("re-parsed font: GlyphAdvance(%q): %w", r, err)
		}
		if got, want := adv.Round(), sf.glyphs[wantGID].advance; got != want {
			return fmt.Errorf("re-parsed font: advance(%q) = %d, want %d", r, got, want)
		}
	}
	return nil
}

// verifyOutlineGeometry independently re-derives every glyph's bounding
// box from the regenerated font (parsed cold by the same trusted
// decoder used to read the source) and compares it against the
// source's own bounding box for the same rune. This is the check that
// actually exercises this generator's hand-written outline writer
// (encodeSimpleGlyph): a Y-axis sign error — the single easiest mistake
// given sfnt.LoadGlyph's Y-increases-down convention versus TrueType's
// own Y-increases-up glyf storage (see loadOutline's doc comment) —
// would flip a glyph upside down and show up here as a bounding box
// with an implausible or mismatched sign, not as a missing glyph or a
// wrong advance width, neither of which verifySubset's checks alone
// would catch.
func verifyOutlineGeometry(src *sfnt.Font, generatedTTF []byte) error {
	regen, err := sfnt.Parse(generatedTTF)
	if err != nil {
		return fmt.Errorf("re-parsing generated font: %w", err)
	}
	var srcBuf, regenBuf sfnt.Buffer
	for _, r := range charset() {
		srcGID, err := src.GlyphIndex(&srcBuf, r)
		if err != nil {
			return err
		}
		wantBounds, _, err := src.GlyphBounds(&srcBuf, srcGID, fixed.I(int(src.UnitsPerEm())), font.HintingNone)
		if err != nil {
			return err
		}
		regenGID, err := regen.GlyphIndex(&regenBuf, r)
		if err != nil {
			return err
		}
		gotBounds, _, err := regen.GlyphBounds(&regenBuf, regenGID, fixed.I(int(regen.UnitsPerEm())), font.HintingNone)
		if err != nil {
			return err
		}
		// Both fonts share the same unitsPerEm (extractSubset copies it
		// verbatim), so the bounds should match exactly, mod the
		// int16-rounding this subset's glyf encoding performs.
		const tolerance = fixed.Int26_6(64) // 1 design unit, in 26.6 fixed point
		diff := func(a, b fixed.Int26_6) fixed.Int26_6 {
			if a > b {
				return a - b
			}
			return b - a
		}
		if diff(wantBounds.Min.X, gotBounds.Min.X) > tolerance ||
			diff(wantBounds.Min.Y, gotBounds.Min.Y) > tolerance ||
			diff(wantBounds.Max.X, gotBounds.Max.X) > tolerance ||
			diff(wantBounds.Max.Y, gotBounds.Max.Y) > tolerance {
			return fmt.Errorf("glyph %q (U+%04X): bounds = %v, want %v (source font's bounds) — a mismatched sign here means an axis got flipped", r, r, gotBounds, wantBounds)
		}
	}
	return nil
}

func charsetFile(runes []rune) []byte {
	var b bytes.Buffer
	b.WriteString("# Generated by scripts/gensubsetfont. Do not edit by hand.\n")
	b.WriteString("# One character per line: U+XXXX  <character>  (name omitted; see the\n")
	b.WriteString("# character itself). This is the exact, complete set of characters the\n")
	b.WriteString("# embedded font subset (notosans-subset.ttf) can render (F4 §3.2).\n")
	fmt.Fprintf(&b, "# %d characters total.\n", len(runes))
	for _, r := range runes {
		fmt.Fprintf(&b, "U+%04X  %c\n", r, r)
	}
	return b.Bytes()
}

// subsetDataGo emits internal/pades/appearance/subset_data.go: the
// rune→GID table and per-GID /W widths, as literal Go data rather than
// a format parsed at runtime (F4 §3.2/§3.3 — no font or table parser
// ships in the release binary; the same reasoning extends to not
// shipping *any* parser, however small, for this generator's own
// intermediate format).
func subsetDataGo(sf *subsetFont) []byte {
	type entry struct {
		r   rune
		gid uint16
	}
	entries := make([]entry, 0, len(sf.runeToNewGID))
	for r, g := range sf.runeToNewGID {
		entries = append(entries, entry{r, g})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].r < entries[j].r })

	var b strings.Builder
	b.WriteString("// Code generated by scripts/gensubsetfont from notosans-subset.ttf. DO NOT EDIT.\n\n")
	b.WriteString("package appearance\n\n")
	fmt.Fprintf(&b, "// subsetTag is the six-uppercase-letter /BaseFont prefix (F4 §3.1).\nconst subsetTag = %q\n\n", subsetTag)
	fmt.Fprintf(&b, "// unitsPerEm is notosans-subset.ttf's own design-unit scale (its head.unitsPerEm).\nconst unitsPerEm = %d\n\n", sf.unitsPerEm)
	b.WriteString("// runeToGID maps every character this subset can draw to its glyph index,\n")
	b.WriteString("// which is also its CID under this font's required /CIDToGIDMap /Identity\n")
	b.WriteString("// (F4 §3.1/§3.3). A rune absent from this map cannot be drawn — see\n")
	b.WriteString("// EncodeCIDs' handling of that case.\n")
	b.WriteString("var runeToGID = map[rune]uint16{\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "\t%#04x: %d, // %c\n", e.r, e.gid, printableOrDot(e.r))
	}
	b.WriteString("}\n\n")

	b.WriteString("// gidWidths holds each glyph's advance width in 1000-unit glyph space\n")
	b.WriteString("// (F4 §3.5's /W array source), indexed by GID; gidWidths[0] is .notdef.\n")
	b.WriteString("var gidWidths = []uint16{\n")
	for i, g := range sf.glyphs {
		w1000 := g.advance * 1000 / int(sf.unitsPerEm)
		fmt.Fprintf(&b, "\t%d, // GID %d\n", w1000, i)
	}
	b.WriteString("}\n\n")

	minX, minY, maxX, maxY := sf.bbox()
	b.WriteString("// Font metrics in 1000-unit glyph space, for the /FontDescriptor this\n")
	b.WriteString("// subset's embedding requires (PDF 32000-1 §9.8.1).\n")
	fmt.Fprintf(&b, "const (\n\tfontAscent    = %d\n\tfontDescent   = %d\n\tfontCapHeight = %d\n\tfontBBoxMinX  = %d\n\tfontBBoxMinY  = %d\n\tfontBBoxMaxX  = %d\n\tfontBBoxMaxY  = %d\n)\n",
		sf.ascent, sf.descent, sf.capHeight, minX, minY, maxX, maxY)
	return []byte(b.String())
}

func printableOrDot(r rune) rune {
	if r == ' ' {
		return '_'
	}
	return r
}
