package pades

import (
	"context"
	"os"
	"testing"

	"github.com/veljaos/liro-bridge/internal/pades/pdf"
)

// blankFixturePath is testdata/pdfs/blank.pdf (Task 1): a single blank
// A4 page, no AcroForm, no existing signature, generated by
// scripts/genblankpdf so it is reproducible rather than a binary
// someone pasted in. Unlike testdata/pdfs/local/*.pdf (real signed
// documents, not committed — see that directory's README), this fixture
// starts from nothing: signing it exercises only the AcroForm, widget
// and strings this project's own writer creates, with none of an
// existing producer's own objects mixed in. That is exactly the
// isolation Task 2 needs: a bug in how this project writes /DA, /T or
// /Lang has nowhere else to hide when the whole AcroForm tree is ours.
const blankFixturePath = "../../testdata/pdfs/blank.pdf"

func blankFixture(t *testing.T) []byte {
	t.Helper()
	data, err := os.ReadFile(blankFixturePath)
	if err != nil {
		t.Fatalf("reading %s (run `go run ./scripts/genblankpdf` from the repo root to generate it): %v", blankFixturePath, err)
	}
	return data
}

// TestSignBlankFixtureProducesSmallVerifyingOutput is Task 1: signing
// the blank fixture must produce a small, independently verifying
// signature — nowhere near the ~670KB a full real fixture (three
// existing revisions, an existing AcroForm, an existing signature)
// produces, which is what makes this fixture useful as a fast
// discriminator for future writer-level bugs.
func TestSignBlankFixtureProducesSmallVerifyingOutput(t *testing.T) {
	sess := newFakeSession(t)
	result, err := SignDocument(context.Background(), blankFixture(t), sess, Options{})
	if err != nil {
		t.Fatalf("SignDocument: %v", err)
	}

	const wantMax = 100 * 1024 // an order of magnitude below a real fixture's ~670KB
	if len(result.Bytes) > wantMax {
		t.Errorf("signed output is %d bytes, want well under %d (a full real fixture is ~670KB)", len(result.Bytes), wantMax)
	}
	t.Logf("signed blank fixture: %d bytes", len(result.Bytes))

	r := verifyResult(t, result.Bytes)
	if len(r.Errors) > 0 || !r.ByteRangeDigestOK || !r.SignatureOK || !r.SigningCertificateOK {
		t.Fatalf("independent verification failed: %+v errors=%v", r, r.Errors)
	}
}

// TestSignBlankFixtureFieldNameIsLiteralString is Task 2's verification
// against the fixture this project's own AcroForm/widget code builds
// from nothing: /T must be a literal string in the output, never hex —
// see internal/pades/pdf/write_test.go for the writer-level unit tests
// this end-to-end check complements.
func TestSignBlankFixtureFieldNameIsLiteralString(t *testing.T) {
	sess := newFakeSession(t)
	result, err := SignDocument(context.Background(), blankFixture(t), sess, Options{})
	if err != nil {
		t.Fatalf("SignDocument: %v", err)
	}

	doc, err := pdf.Parse(result.Bytes)
	if err != nil {
		t.Fatalf("re-parsing signed output: %v", err)
	}
	rootRef, ok := doc.Trailer().Get(pdf.Name("Root")).(pdf.Reference)
	if !ok {
		t.Fatal("trailer /Root is not an indirect reference")
	}
	catalog, ok := doc.ResolveDict(rootRef)
	if !ok {
		t.Fatal("/Root does not resolve to a dictionary")
	}
	acroForm, ok := doc.ResolveDict(catalog.Get(pdf.Name("AcroForm")))
	if !ok {
		t.Fatal("/AcroForm does not resolve to a dictionary")
	}
	fields, _ := doc.Resolve(acroForm.Get(pdf.Name("Fields"))).(pdf.Array)
	if len(fields) != 1 {
		t.Fatalf("len(Fields) = %d, want 1", len(fields))
	}
	widget, ok := doc.ResolveDict(fields[0])
	if !ok {
		t.Fatal("the field entry does not resolve to a dictionary")
	}
	fieldName, ok := widget.Get(pdf.Name("T")).(pdf.String)
	if !ok {
		t.Fatal("the widget's /T is not a String")
	}
	if string(fieldName) != "Liro-Signature-1" {
		t.Fatalf("/T = %q, want %q", fieldName, "Liro-Signature-1")
	}

	// The parsed model can't say which syntax produced the value it
	// decoded (internal/pades/pdf.String's own doc comment), so the only
	// way to confirm the writer chose literal over hex is to look at the
	// bytes it actually emitted.
	if !containsLiteralString(t, result.Bytes, "T", "Liro-Signature-1") {
		t.Errorf("output does not contain /T (Liro-Signature-1) as a literal string")
	}
	if containsHexString(t, result.Bytes, "T") {
		t.Errorf("output hex-encodes /T somewhere — it must be written as a literal string")
	}
}

// TestSignBlankFixtureAcroFormIsIndirect confirms the blank fixture's
// case stays on the working side of the four-case table in
// docs/decisions.md: blank.pdf has no pre-existing /AcroForm to preserve
// the shape of, so BuildPlaceholder still creates a fresh, indirect
// /AcroForm object exactly as before this fix — only a *pre-existing
// direct* /AcroForm is now preserved as direct; a document with none at
// all is unaffected and must keep working the same way it always did.
func TestSignBlankFixtureAcroFormIsIndirect(t *testing.T) {
	sess := newFakeSession(t)
	result, err := SignDocument(context.Background(), blankFixture(t), sess, Options{})
	if err != nil {
		t.Fatalf("SignDocument: %v", err)
	}

	direct, _ := acroFormDirect(t, result.Bytes)
	if direct {
		t.Fatalf("blank fixture's signed /AcroForm is a direct dictionary, want an indirect reference (the fixture had no /AcroForm to preserve the shape of)")
	}
}

// TestSignBlankFixturePreservesIDAsHexString is the other half of Task
// 2's rule: the fixture's own /ID (genuinely binary — a digest, not
// text, see scripts/genblankpdf) is carried forward into the new
// revision's trailer unmodified (internal/pades/pdf/incremental.go's
// updateTrailer) and re-serialised there. It must still come out as a
// hex string — the fix that makes /DA, /T and /Lang literal must not
// also force binary content through literal-string escaping.
func TestSignBlankFixturePreservesIDAsHexString(t *testing.T) {
	sess := newFakeSession(t)
	result, err := SignDocument(context.Background(), blankFixture(t), sess, Options{})
	if err != nil {
		t.Fatalf("SignDocument: %v", err)
	}
	if !containsHexString(t, result.Bytes, "ID") {
		// /ID in the trailer is an array of two hex strings, e.g.
		// "/ID [<...> <...>]" — containsHexString's "/ID <...>" pattern
		// matches the first element directly.
		t.Errorf("output does not preserve /ID as a hex string in the new trailer")
	}
}
