package render

import (
	_ "embed"
	"log/slog"
	"strings"
	"sync"
)

// The substitute fonts. When a document does not embed a font — every
// use of Helvetica, Times or Courier, and every font a producer assumed
// the reader already has — there is no outline in the file to draw, and
// a preview that drew nothing would show a page of blank lines where its
// text is. Substituting is what every PDF reader does in the same
// situation, and it is safe here for one specific reason: the metrics
// are still the document's own (see pdfFont), so every word starts and
// ends where the real one does. Only the shapes are ours.
//
// Two faces rather than one, because the choice between them is
// visible at a glance on a page and free to make: Serbian legal
// documents are set in a serif face far more often than not, and a
// contract previewed in a sans-serif when it will print as Times reads
// as the wrong document.
//
// Both are subsets of Noto (SIL Open Font License 1.1), generated by
// scripts/gensubsetfont --set preview; the character sets are recorded
// beside them in preview-sans-charset.txt and preview-serif-charset.txt.

//go:embed preview-sans.ttf
var previewSansTTF []byte

//go:embed preview-serif.ttf
var previewSerifTTF []byte

var (
	substituteOnce  sync.Once
	substituteSans  *ttfFont
	substituteSerif *ttfFont
)

func loadSubstitutes() {
	substituteOnce.Do(func() {
		var err error
		if substituteSans, err = parseTTF(previewSansTTF); err != nil {
			slog.Error("render: the embedded sans substitute font did not parse", "error", err)
		}
		if substituteSerif, err = parseTTF(previewSerifTTF); err != nil {
			slog.Error("render: the embedded serif substitute font did not parse", "error", err)
		}
	})
}

// serifNames are the base font names that mean "this page is set in a
// serif face". The /FontDescriptor has a Serif flag for exactly this
// question and real producers set it wrongly often enough — Word writes
// a descriptor for Times New Roman with the flag clear — that the name
// the document itself chose is the better evidence.
var serifNames = []string{
	"times", "serif", "roman", "georgia", "garamond", "book", "minion",
	"cambria", "palatino", "century", "constantia", "utopia", "charter",
	"pt serif", "ptserif", "libertine", "georgi",
}

// substituteFor picks the face to stand in for a font that is not
// embedded. A monospaced font gets the sans face: what makes monospaced
// text look right is its advance widths, which come from the document
// and are honoured exactly, not the shapes of its letters.
func substituteFor(baseFont string) *ttfFont {
	loadSubstitutes()
	name := strings.ToLower(baseFont)
	// A subset prefix ("BCDEEE+TimesNewRomanPSMT") is not part of the
	// name; the family is what follows the plus.
	if i := strings.IndexByte(name, '+'); i >= 0 && i+1 < len(name) {
		name = name[i+1:]
	}
	for _, s := range serifNames {
		if strings.Contains(name, s) {
			if substituteSerif != nil {
				return substituteSerif
			}
			break
		}
	}
	return substituteSans
}
