// Code generated by scripts/gensubsetfont from notosans-bold-subset.ttf. DO NOT EDIT.

package appearance

// The bold face carries no rune -> GID table of its own: it is built from
// the same character set, in the same sorted order, as the regular face, so
// runeToGID (subset_data.go) addresses both — which is also why one
// /ToUnicode CMap serves both embedded fonts (D-209). What differs between
// two weights of one family is the metrics below.

// gidWidthsBold holds each bold glyph's advance width in 1000-unit glyph
// space (the bold face's /W array source), indexed by GID; gidWidthsBold[0]
// is .notdef.
var gidWidthsBold = []uint16{
	0,    // GID 0
	260,  // GID 1
	282,  // GID 2
	479,  // GID 3
	646,  // GID 4
	572,  // GID 5
	902,  // GID 6
	750,  // GID 7
	266,  // GID 8
	339,  // GID 9
	339,  // GID 10
	542,  // GID 11
	572,  // GID 12
	285,  // GID 13
	320,  // GID 14
	281,  // GID 15
	415,  // GID 16
	572,  // GID 17
	572,  // GID 18
	572,  // GID 19
	572,  // GID 20
	572,  // GID 21
	572,  // GID 22
	572,  // GID 23
	572,  // GID 24
	572,  // GID 25
	572,  // GID 26
	281,  // GID 27
	285,  // GID 28
	572,  // GID 29
	572,  // GID 30
	572,  // GID 31
	477,  // GID 32
	898,  // GID 33
	692,  // GID 34
	665,  // GID 35
	642,  // GID 36
	732,  // GID 37
	560,  // GID 38
	549,  // GID 39
	724,  // GID 40
	765,  // GID 41
	389,  // GID 42
	331,  // GID 43
	664,  // GID 44
	559,  // GID 45
	943,  // GID 46
	813,  // GID 47
	791,  // GID 48
	621,  // GID 49
	791,  // GID 50
	656,  // GID 51
	551,  // GID 52
	577,  // GID 53
	756,  // GID 54
	650,  // GID 55
	967,  // GID 56
	670,  // GID 57
	626,  // GID 58
	579,  // GID 59
	331,  // GID 60
	415,  // GID 61
	331,  // GID 62
	572,  // GID 63
	411,  // GID 64
	365,  // GID 65
	599,  // GID 66
	632,  // GID 67
	516,  // GID 68
	632,  // GID 69
	597,  // GID 70
	387,  // GID 71
	632,  // GID 72
	650,  // GID 73
	299,  // GID 74
	298,  // GID 75
	620,  // GID 76
	298,  // GID 77
	975,  // GID 78
	650,  // GID 79
	625,  // GID 80
	632,  // GID 81
	632,  // GID 82
	447,  // GID 83
	502,  // GID 84
	434,  // GID 85
	650,  // GID 86
	571,  // GID 87
	856,  // GID 88
	578,  // GID 89
	571,  // GID 90
	493,  // GID 91
	394,  // GID 92
	551,  // GID 93
	394,  // GID 94
	572,  // GID 95
	260,  // GID 96
	614,  // GID 97
	424,  // GID 98
	614,  // GID 99
	642,  // GID 100
	516,  // GID 101
	642,  // GID 102
	516,  // GID 103
	732,  // GID 104
	645,  // GID 105
	551,  // GID 106
	502,  // GID 107
	579,  // GID 108
	493,  // GID 109
	765,  // GID 110
	331,  // GID 111
	1034, // GID 112
	1063, // GID 113
	778,  // GID 114
	766,  // GID 115
	692,  // GID 116
	649,  // GID 117
	662,  // GID 118
	563,  // GID 119
	776,  // GID 120
	561,  // GID 121
	997,  // GID 122
	593,  // GID 123
	791,  // GID 124
	693,  // GID 125
	733,  // GID 126
	943,  // GID 127
	770,  // GID 128
	777,  // GID 129
	762,  // GID 130
	623,  // GID 131
	645,  // GID 132
	577,  // GID 133
	645,  // GID 134
	902,  // GID 135
	667,  // GID 136
	776,  // GID 137
	719,  // GID 138
	1067, // GID 139
	596,  // GID 140
	624,  // GID 141
	596,  // GID 142
	475,  // GID 143
	637,  // GID 144
	584,  // GID 145
	866,  // GID 146
	515,  // GID 147
	674,  // GID 148
	616,  // GID 149
	623,  // GID 150
	837,  // GID 151
	656,  // GID 152
	621,  // GID 153
	650,  // GID 154
	635,  // GID 155
	524,  // GID 156
	505,  // GID 157
	571,  // GID 158
	810,  // GID 159
	577,  // GID 160
	650,  // GID 161
	637,  // GID 162
	953,  // GID 163
	653,  // GID 164
	298,  // GID 165
	897,  // GID 166
	926,  // GID 167
	653,  // GID 168
	650,  // GID 169
	500,  // GID 170
	1000, // GID 171
	217,  // GID 172
	286,  // GID 173
	445,  // GID 174
	513,  // GID 175
	855,  // GID 176
}

// Bold font metrics in 1000-unit glyph space, for the bold face's own
// /FontDescriptor (PDF 32000-1 §9.8.1).
const (
	boldFontAscent    = 1069
	boldFontDescent   = -293
	boldFontCapHeight = 714
	boldFontBBoxMinX  = -74
	boldFontBBoxMinY  = -240
	boldFontBBoxMaxX  = 1018
	boldFontBBoxMaxY  = 934
)
