package ui

// Intent is one of the four outcome-colour families the design system
// defines (Task 6, F5 first-real-run review): every outcome the
// agent's windows display resolves to exactly one of these, then to
// the CSS class "liro-outcome-<intent>" (intents.css, generated by
// scripts/synctokens from its own IntentFamilyColor map) — never to a
// colour chosen ad hoc by the code doing the mapping.
type Intent string

const (
	IntentPositive Intent = "positive"
	IntentWarning  Intent = "warning"
	IntentNegative Intent = "negative"
	IntentCaution  Intent = "caution"
)
